services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build: ./web
    command: bash -c "./wait_for_selenium.sh && gunicorn --bind 0.0.0.0:4000 manage:app"
    expose:
    - 4000
    env_file:
      - ./.env.prod
    depends_on:
      - selenium
  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
    shm_size: 2g
