services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:4000 manage:app
    expose:
    - 4000
    env_file:
      - ./.env.prod
